/*
 * Copyright (C) 2017 OrionStar Technology Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * 以下为中文简体文本字符信息
 * 默认为简体中文，以下文字信息分为两类，分开存储
 * 第一类：需要在其他语音的js文件内同步添加（需翻译）。
 * 第二类：不需要适配国际化文字信息（无需翻译）
 */
export default {
    changeOpk: '應用切換',
    settings: '設定',
    errorCode: '錯誤碼：%s',
    navEndTask: '結束任務',
    reboot_robot: '從啓恢復',
    cancel: '取消',
    confirm: '確認',
    overRunTitle: '機械人嘅車轆已多次遇到問題',
    overRunSubTitle: '請檢查車轆是否被雜物卡住或運送超載\n請你排除問題後再點擊“恢復工作”',
    noProcess: '暫時唔處理住',
    resumeWork: '恢復工作',
    pointArrive: '已到達%s',
    thisIsGreetPoint: '呢度就係%s喇',
    repositionHint: '請檢查定位係咪成功',
    navi_fatal_error: '導航出現左問題呀',
    nav_getLost_tts: '我搵唔到去往%s既路喇，唔該幫我推到去附近嘅定位標籤下方再試下啦',
    nav_fatalError_tts: '導航出現左問題呀，請點擊從啓按鈕幫我恢復正常呀',
    warningTitle_getLost: '我揾唔到路啊',
    warningTitle_fatalError: '導航出現左問題呀',
    warningHint_getLost: '唔該幫我推到去附近嘅定位標籤下方再試下啦',
    warningHint_fatalError: '請點擊從啓按鈕幫我恢復正常丫',
    warning_avoid_subTitle: '請確保我冇被障礙物遮擋啊',
    wheelErrorTts: '機械人嘅車轆已多次遇到問題。\n請檢查車轆是否被雜物卡住或運送超載\n請你排除問題之後，再點擊“恢復工作”。',
    continue_shipping: '從試',
    contactHint: '如持續從啓仍出現問題，請聯系售後',
    avoidTtsArray: [
        '哎呀,我被擋住左呀,唔該讓一讓比我丫',
        '唔好意思呀,唔該讓一讓,機械人嚟喇',
        '你冇睇錯呀,機械人嚟喇',
        '靚仔靚女,麻煩讓一下丫,機械人嚟喇',
        '我地遲d再傾丫,我做埋d野先啊',
        '靚仔靚女, 麻煩讓一下我丫',
        '比個位我行丫,人地仲要做野嫁,錫晒你呀',
        '唔好意思讓一讓唔該晒',
        '呠呠,機械人嚟喇,借一借過丫唔該',
        '滾水呀,麻煩讓一讓',
        '麻煩讓一讓丫,我遲到喇',
        '比個位我行丫,做完野再同你玩丫',
        '我要過去喇,麻煩讓一讓丫',
        '哥哥姐姐,幫忙讓一讓條路丫',
        '唔該讓一讓呀,我趕緊路呀',
        '唔該讓一讓丫,人地只是咁啱路過,仲做緊野嫁',
        '唔該你比我過去丫,無為要機械人難做丫'
    ],
    endTask: '結束任務',
    standbyPoint: '待機點',
    receptionPoint: '接待點',
    chargePoint: '回充點',
    chargePile: '充電樁',
    locationPoint: '定位點',
    setTaskAcceptPoint: '任務受理點設定',
    emptyPoints: '當前冇可配置嘅地點',
    setPointsInMap: '請先去地圖工具設定地點哦',
    waitOrderText: '已進入跑堂模式\n我係度等緊顧客掃描“小程式碼”',
    meal: '送餐',
    welcome: '攬客',
    cruise: '巡航',
    leading: '帶位',
    plateRecycling: '回盤',
    switchDeskTTSArray: ['當顧客掃描跑堂小程式碼之後，我就可以開始服務喇'],
    clickTask: '點擊選擇服務，我都可以完成㗎',
    pushFood: '我要催菜',
    waiter: '搵服務人員',
    lackTableware: '缺少餐具',
    clearTable: '執拾餐檯',
    passThanks: '唔駛喇，唔該（%ds）',
    tablewareTitle: '請選擇下方餐具',
    bowl: '碗',
    plate: '餐盤',
    chopsticks: '筷子',
    cup: '杯',
    fork: '叉',
    tableKnife: '餐刀',
    spoon: '勺子',
    completeTableware: '一整套餐具',
    big: '大',
    small: '細',
    wineGlass: '酒杯',
    drinkingCup: '汽水杯',
    soup: '湯勺',
    colander: '漏勺',
    smallSpoon: '小勺',
    complete: '完成',
    completeWithCount: '完成（%ds）',
    confirmTablewareTTS: '好嘅，收到任務喇',
    taskConfirm: '確認任務',
    tableNum: '檯號：',
    taskType: '任務類型：',
    handleTask: '處理任務',
    toDoTask: '待辦任務',
    cancelTask: '取消任務',
    cancelTaskWarn: '任務取消將不能恢復，請確認係咪取消',
    taskCanceled: '當前任務已被取消',
    robotDeliveryTableware: '機械人遞送餐具',
    robotDeliveryTablewareWithTier: '機械人遞送餐具（所選層數：%d）',
    humanDeliveryTableware: '人工遞送餐具',
    robotReply: '機械人回復',
    noNeedRobotReply: '無需機械人回復',
    taskCancelSuccess: '取消任務成功',
    pushFoodTitle: '嘅客人，希望催促下菜品',
    lackTablewareTitle: '嘅客人，需要：',
    clearTableTitle: '嘅客人，希望過去執拾一下餐檯',
    lookWaiterTitle1: '嘅客人，需要服務人員過去一下',
    tableArriveText1: '你嘅餐具黎喇\n係第',
    tableArriveText2: '層，麻煩自己攞丫',
    takeOut: '攞完喇（%d）',
    replyCustomer: '開始執行',
    getNewTask: '收到新任務喇',
    callPositionTaskTitle: '當前任務數量（1）',
    pendingTaskCount: '你有%d條待辦任務，請儘快處理呀',
    currentTaskCount: '當前任務數量（%d）',
    taskCompleteFeedback: '任務處理完畢，我而家去回復顧客喇',
    continueWorkGoodbye: '我繼續做嘢喇，需要幫助既話可以隨時嗌我，遲d見',
    tablewareTaskTrick: ' 你缺少嘅餐具嚟喇，喺第%d層\n麻煩自己攞丫',
    tablewareTaskTrickTts: '你爭咗嘅餐具嚟喇，係第%d層，麻煩你攞一下呀',
    okGetTaskHandle: '好既，收到任務喇，我而家去處理',
    netError: '網絡異常',
    taskHandleComplete: '任務經已處理完畢',
    taskTakeTTS: '任務領取成功，請選擇要用嘅方式處理',
    humanReplyTTS: '%s枱%s任務已經處理完畢，請儘快回復顧客',
    humanDeliveryTTS: '%s枱缺少餐具的任務已經處理完畢，請儘快攞畢顧客啊',
    tablewareEnterTTS: '點擊螢幕選擇你需要嘅餐具，用加號掣選擇數量，選好後，記得選擇下面嘅完成按鈕啊',
    hurryTaskCompleteTTS: '你啱啱交比我幫你催菜，已經幫您催過喇，服務人員話馬上就得喇，請再稍等一陣丫',
    waiterTaskCompleteTTS: '你啱啱嗌我幫你搵服務人員，我已經幫你通知左喇，佢地即刻黎，請稍等一陣',
    clearTableTaskCompleteTTS: '你需要嘅執拾餐檯任務，已經幫你通知左服務人員喇，佢地嚟緊，請稍等',
    tierPickTitle: '層數選擇',
    tierPickSubTitle: '請選擇放置餐具既層數',
    robotReplayTTS: '撳下面開始執行嘅掣，我就去幫你回復顧客喇',
    robotDeliveryTTS: '撳下面開始執行嘅掣，我就幫你送餐具畢顧客喇',
    errorToast: '由於網絡同步問題，該任務已被其他人搶先處理，您無需理會（%s）',
    taskDialogTTS: '請確認你嘅枱號和任務是否正確',
    callPositionTTS: '點擊或語音選擇您需要的服務，我都可以完成啊',
    yes: '是',
    no: '否',
    birthday1TTS: '%s，你好呀，祝你生日快樂，你嘅%s，%s，想同你講：%s',
    thanksYouCanGo: '唔該晒，可以返去喇',
    convertHurryTaskTTS: '好嘅，我宜加去幫你催菜',
    convertTablewareTaskTTS: '好嘅，我宜家就去搵服務人員，幫你準備餐具啊',
    convertWaiterTaskTTS: '收到，我宜加去幫你搵服務人員丫',
    convertClearTaskTTS: '好嘅，我宜加去幫你通知服務人員過黎執拾餐枱啊',
    goWayCallMe: '我走喇，有需要可以隨時再叫我啊',
    birthdayLocalAsrArray: [
        '唔該晒，可以返去喇',
        '你可以走了',
        '拜拜',
        '唔該曬',
        '不洗了',
        '走啦'
    ],
    cannotArriveTip: '*當前餐檯，機械人無法到達',
    deskSettings: '跑堂設定',
    nav_multiRobotError_tts: '多機調度出現異常，請嘗試從啓或者聯絡售後人員',
    // eslint-disable-next-line @typescript-eslint/camelcase
    warningHint_multiRobotError: '請對此畫面拍照並聯絡售後人員',
    // eslint-disable-next-line @typescript-eslint/camelcase
    warningTitle_multiRobotError: '多機調度出現異常',
    deskService: '跑堂',
    warningTitlePathInvalid: '我搵唔到巡航路線呀',
    warningSubTitlePathInvalid: '請繪制巡航路線然後發布呀',
    warningTitleRobotOutOfPath: '我脫離左巡航路線呀',
    warningSubTitleRobotOutOfPath: '唔該將我推返去巡航路線嘅範圍裏面呀',
    waringTitleTargetOutOfPath: '目的地唔係巡航路線範圍裏面呀',
    warningSubTitleTargetOutOfPath: '請檢查巡航路線然後重新發布呀'
};