/*
 * Copyright (C) 2017 OrionStar Technology Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * 以下为中文简体文本字符信息
 * 默认为简体中文，以下文字信息分为两类，分开存储
 * 第一类：需要在其他语音的js文件内同步添加（需翻译）。
 * 第二类：不需要适配国际化文字信息（无需翻译）
 */
export default {
    changeOpk: '应用切换',
    settings: '设置',
    errorCode: '错误码:%s',
    navEndTask: '结束任务',
    reboot_robot: '重启恢复',
    cancel: '取消',
    confirm: '确认',
    overRunTitle: '机器人轮子已多次遇到问题',
    overRunSubTitle: '请检查轮子是否被杂物卡住或运送超载 \n请您排除问题后再点击“恢复工作”',
    noProcess: '暂不处理',
    resumeWork: '恢复工作',
    pointArrive: '已到达%s',
    thisIsGreetPoint: '这里就是%s啦',
    repositionHint: '请检查是否定位成功',
    navi_fatal_error: '导航出现问题啦',
    nav_getLost_tts: '我找不到去往%s的路啦，请将我推到附近的定位标签下方重试吧',
    nav_fatalError_tts: '导航出现问题啦，请点击重启按钮帮我恢复正常吧',
    warningTitle_getLost: '找不到路啦',
    warningTitle_fatalError: '导航出现问题啦',
    warningHint_getLost: '请把我推到附近的定位标签下方重试吧',
    warningHint_fatalError: '请点击重启按钮帮我恢复正常吧',
    warning_avoid_subTitle: '请确保我没有被障碍物遮挡哦',
    wheelErrorTts: '机器人轮子已多次遇到问题。\n请检查轮子是否被杂物卡住或运送超载\n请您排除问题后，再点击“恢复工作”。',
    continue_shipping: '重试',
    contactHint: '如持续重启仍出现问题，请联系售后',
    avoidTtsArray: ['哎呀，我被挡住了，请帮忙给让条路呀', '不好意思，请您让一下，机器人来啦',
        '叮当叮当，机器人来啦', '亲亲，帮忙让一下呀，机器人来啦', '请您不要太迷恋我，人家忙着呢',
        '英俊潇洒的你，美丽迷人的你就让一下我啦', '小可爱，不要挡在我前面惹，人家还要干活啦',
        '让一让啦好不好骂，人家还要工作呢', '叮拎叮拎，机器人来咯，借过一下下', '帅气美丽的哥哥姐姐，请让一下下呀',
        '麻烦让一下下啦，人家要迟到啦', '哥哥姐姐让一下，等我下班再来找你玩吧', '客官，麻烦让一下惹，我要过去咯',
        '小哥哥小姐姐，帮忙让条路呀', '请让一让呀，宝宝有小情绪啦', '请让一让， 人家只是个路过的宝宝嘿嘿',
        '求求你让我过去吧，做个机器人太难了'],
    endTask: '结束任务',
    standbyPoint: '待机点',
    receptionPoint: '接待点',
    chargePoint: '回充点',
    chargePile: '充电桩',
    locationPoint: '定位点',
    setTaskAcceptPoint: '任务受理点设置',
    emptyPoints: '当前没有可配置的地点',
    setPointsInMap: '请先去地图工具设置地点哦',
    waitOrderText: '已进入跑堂模式\n我正在等待顾客扫描“小程序码”',
    meal: '送餐',
    welcome: '揽客',
    cruise: '巡航',
    leading: '领位',
    plateRecycling: '回盘',
    switchDeskTTSArray: [
        '当顾客扫描跑堂小程序码后，我就可以开始服务了',
    ],
    clickTask: '点击或语音选择服务，我都可以完成',
    pushFood: '我要催菜',
    waiter: '找服务人员',
    lackTableware: '缺少餐具',
    clearTable: '收拾桌子',
    passThanks: '不用了，谢谢（%ds）',
    tablewareTitle: '请选择下方餐具',
    bowl: '碗',
    plate: '餐盘',
    chopsticks: '筷子',
    cup: '杯子',
    fork: '叉子',
    tableKnife: '餐刀',
    spoon: '勺子',
    completeTableware: '整套餐具',
    big: '大',
    small: '小',
    wineGlass: '酒杯',
    drinkingCup: '饮料杯',
    soup: '汤勺',
    colander: '漏勺',
    smallSpoon: '小勺',
    complete: '完成',
    completeWithCount: '完成（%ds）',
    confirmTablewareTTS: '好的，收到任务啦',
    taskConfirm: '任务确认',
    tableNum: '桌号：',
    taskType: '任务类型：',
    handleTask: '处理任务',
    toDoTask: '待办任务',
    cancelTask: '取消任务',
    cancelTaskWarn: '任务取消将不能恢复，请确认是否取消',
    taskCanceled: '当前任务已被取消',
    robotDeliveryTableware: '机器人递送餐具',
    robotDeliveryTablewareWithTier: '机器人递送餐具（所选层数：%d）',
    humanDeliveryTableware: '人工递送餐具',
    robotReply: '机器人回复',
    noNeedRobotReply: '无需机器人回复',
    taskCancelSuccess: '任务取消成功',
    pushFoodTitle: '的客人，希望催促一下菜品',
    lackTablewareTitle: '的客人，需要：',
    clearTableTitle: '的客人，希望收拾一下桌子',
    lookWaiterTitle1: '的客人，需要服务人员过去一下',
    tableArriveText1: '您的餐具来啦\n在第',
    tableArriveText2: '层，请自己拿取',
    takeOut: '拿完了（%d）',
    replyCustomer: '开始执行',
    getNewTask: '收到新任务啦',
    callPositionTaskTitle: '当前任务数量（1）',
    pendingTaskCount: '你有%d条待办任务，请尽快处理呀',
    currentTaskCount: '当前任务数量（%d）',
    taskCompleteFeedback: '任务处理完啦，我这就去和顾客反馈啦',
    continueWorkGoodbye: '我继续工作啦，需要帮助可以随时叫我哦，白白',
    tablewareTaskTrick: '您缺少的餐具来啦，在第%d层\n请自己拿取呀',
    tablewareTaskTrickTts: '您缺少的餐具来啦，在第%d层，请自己拿取呀',
    okGetTaskHandle: '好的，收到任务啦，我这就去处理',
    netError: '网络异常',
    taskHandleComplete: '任务已经处理完啦',
    taskTakeTTS: '任务领取成功，请选择要用什么方式处理哦',
    humanReplyTTS: '%s桌%s任务已经处理完成啦，请尽快回复顾客呀',
    humanDeliveryTTS: '%s桌缺少餐具的任务已经处理完成啦，请尽快拿给顾客哦',
    tablewareEnterTTS: '点击屏幕或语音选择您需要的餐具，用加号按钮选择数量，选好后，记得选择下方的完成按钮哦',
    hurryTaskCompleteTTS: '您刚才让我帮您催菜，我已经帮您催过啦，服务人员说马上就好哦，请再等一小会儿吧',
    waiterTaskCompleteTTS: '您刚才让我帮您找服务人员，我已经帮您通知到啦，他们马上就来，请稍等一小会儿哦',
    clearTableTaskCompleteTTS: '您的收拾桌子任务，已经帮您通知服务人员啦，他们马上就来，请稍等哦',
    tierPickTitle: '层数选择',
    tierPickSubTitle: '请选择放置餐具的层数',
    robotReplayTTS: '点击下方开始执行按钮，我就帮你去回复顾客啦',
    robotDeliveryTTS: '点击下方开始执行按钮，我就帮你送餐具给顾客啦',
    errorToast: '由于网络同步问题，该任务已被其他人抢先处理，您无需理会（%s)',
    taskDialogTTS: '请确认您的桌号和任务是否正确',
    callPositionTTS: '点击或语音选择您需要的服务，小豹都可以完成哦',
    yes: '是',
    no: '否',
    birthday1TTS: '%s,你好呀，祝你生日快乐，您的%s,%s,想对你说:%s',
    thanksYouCanGo: '谢谢，你可以走了',
    convertHurryTaskTTS: '好嘞,我这就帮您催菜去',
    convertTablewareTaskTTS: '好哒,我这就去找服务人员，帮您准备餐具啦',
    convertWaiterTaskTTS: '收到,我去帮你找服务人员去啦',
    convertClearTaskTTS: '好嘞,我这就去帮您通知服务人员来收拾桌子',
    goWayCallMe: '我走啦, 有需要可以随时再叫我哦',
    birthdayLocalAsrArray: [
        '谢谢你可以走了',
        "你可以走了",
        "再见",
        "谢谢",
        "不用了",
        "走吧",
    ],
    cannotArriveTip: '* 当前餐桌，机器人无法到达',
    deskSettings: '跑堂设置',
    nav_multiRobotError_tts: '多机调度出现异常，请尝试重启或联系售后人员',
    // eslint-disable-next-line @typescript-eslint/camelcase
    warningHint_multiRobotError: '请对此画面拍照并联系售后人员',
    // eslint-disable-next-line @typescript-eslint/camelcase
    warningTitle_multiRobotError: '多机调度出现异常',
    deskService: '跑堂',
    warningTitlePathInvalid: '我没有找到巡线',
    warningSubTitlePathInvalid: '请绘制巡线并发布',
    warningTitleRobotOutOfPath: '我脱离巡线了',
    warningSubTitleRobotOutOfPath: '请把我推到巡线范围内',
    waringTitleTargetOutOfPath: '目的地不在巡线范围内',
    warningSubTitleTargetOutOfPath: '请检查巡线并重新发布'
};
