/*
 * Copyright (C) 2017 OrionStar Technology Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * 以下为中文简体文本字符信息
 * 默认为简体中文，以下文字信息分为两类，分开存储
 * 第一类：需要在其他语音的js文件内同步添加（需翻译）。
 * 第二类：不需要适配国际化文字信息（无需翻译）
 */
export default {
    changeOpk: '應用切換',
    settings: '設定',
    errorCode: '錯誤碼：%s',
    navEndTask: '結束任務',
    reboot_robot: '重啓恢復',
    cancel: '取消',
    confirm: '確認',
    overRunTitle: '機器人輪子已多次遇到問題',
    overRunSubTitle: '請檢查輪子是否被雜物卡住或運送超載\n請您排除問題後再點擊“恢復工作”',
    noProcess: '暫不處理',
    resumeWork: '恢復工作',
    pointArrive: '已到達%s',
    thisIsGreetPoint: '這裡就是%s啦',
    repositionHint: '請檢查是否定位成功',
    navi_fatal_error: '導航出現問題啦',
    nav_getLost_tts: '我找不到去往%s的路啦，請將我推到附近的定位標籤下方重試吧',
    nav_fatalError_tts: '導航出現問題啦，請點擊重啓按鈕幫我恢復正常吧',
    warningTitle_getLost: '找不到路啦',
    warningTitle_fatalError: '導航出現問題啦',
    warningHint_getLost: '請把我推到附近的定位標籤下方重試吧',
    warningHint_fatalError: '請點擊重啓按鈕幫我恢復正常吧',
    warning_avoid_subTitle: '請確保我沒有被障礙物遮擋哦',
    wheelErrorTts: '機器人輪子已多次遇到問題。\n請檢查輪子是否被雜物卡住或運送超載\n請您排除問題後，再點擊“恢復工作”。',
    continue_shipping: '重試',
    contactHint: '如持續重啓仍出現問題，請聯系售後',
    avoidTtsArray: [
        '哎呀，我被擋住了,請幫忙給讓條路呀',
        '不好意思，請您讓一下，機器人來啦',
        '叮噹叮噹,機器人來啦',
        '親親,幫忙讓一下呀,機器人來啦',
        '請您不要太迷戀我,人家忙著呢',
        '英俊瀟灑的你,美麗迷人的你就讓一下我啦',
        '小可愛,不要擋在我前面惹,人家還要幹活啦',
        '讓一讓啦好不好罵,人家還要工作呢',
        '叮拎叮拎,機器人來咯,借過一下下',
        '帥氣美麗的哥哥姐姐,請讓一下下呀',
        '麻煩讓一下下啦,人家要遲到啦',
        '哥哥姐姐讓一下,等我下班再來找你玩吧',
        '客官,麻煩讓一下惹,我要過去咯',
        '小哥哥小姐姐,幫忙讓條路呀',
        '請讓一讓呀,寶寶有小情緒啦',
        '請讓一讓,人家只是個路過的寶寶嘿嘿',
        '求求你讓我過去吧,做個機器人太難了'
    ],
    endTask: '結束任務',
    standbyPoint: '待機點',
    receptionPoint: '接待點',
    chargePoint: '回充點',
    chargePile: '充電樁',
    locationPoint: '定位點',
    setTaskAcceptPoint: '任務受理點設定',
    emptyPoints: '當前沒有可配置的地點',
    setPointsInMap: '請先去地圖工具設定地點哦',
    waitOrderText: '已進入跑堂模式\n我正在等待顧客掃描“小程式碼”',
    meal: '送餐',
    welcome: '攬客',
    cruise: '巡航',
    leading: '領位',
    plateRecycling: '回盤',
    switchDeskTTSArray: ['當顧客掃描跑堂小程式碼後，我就可以開始服務了'],
    clickTask: '點擊選擇服務，我都可以完成',
    pushFood: '我要催菜',
    waiter: '找服務人員',
    lackTableware: '缺少餐具',
    clearTable: '收拾桌子',
    passThanks: '不用了，謝謝（%ds）',
    tablewareTitle: '請選擇下方餐具',
    bowl: '碗',
    plate: '餐盤',
    chopsticks: '筷子',
    cup: '杯子',
    fork: '叉子',
    tableKnife: '餐刀',
    spoon: '勺子',
    completeTableware: '整套餐具',
    big: '大',
    small: '小',
    wineGlass: '酒杯',
    drinkingCup: '飲料杯',
    soup: '湯勺',
    colander: '漏勺',
    smallSpoon: '小勺',
    complete: '完成',
    completeWithCount: '完成（%ds）',
    confirmTablewareTTS: '好的，收到任務啦',
    taskConfirm: '任務確認',
    tableNum: '桌號：',
    taskType: '任務類型：',
    handleTask: '處理任務',
    toDoTask: '待辦任務',
    cancelTask: '取消任務',
    cancelTaskWarn: '任務取消將不能恢復，請確認是否取消',
    taskCanceled: '當前任務已被取消',
    robotDeliveryTableware: '機器人遞送餐具',
    robotDeliveryTablewareWithTier: '機器人遞送餐具（所選層數：%d）',
    humanDeliveryTableware: '人工遞送餐具',
    robotReply: '機器人回復',
    noNeedRobotReply: '無需機器人回復',
    taskCancelSuccess: '任務取消成功',
    pushFoodTitle: '的客人，希望催促一下菜品',
    lackTablewareTitle: '的客人，需要：',
    clearTableTitle: '的客人，希望收拾一下桌子',
    lookWaiterTitle1: '的客人，需要服務人員過去一下',
    tableArriveText1: '您的餐具來啦\n在第',
    tableArriveText2: '層，請自己拿取',
    takeOut: '拿完了（%d）',
    replyCustomer: '開始執行',
    getNewTask: '收到新任務啦',
    callPositionTaskTitle: '當前任務數量（1）',
    pendingTaskCount: '你有%d條待辦任務，請儘快處理呀',
    currentTaskCount: '當前任務數量（%d）',
    taskCompleteFeedback: '任務處理完啦，我這就去和顧客回饋啦',
    continueWorkGoodbye: '我繼續工作啦，需要幫助可以隨時叫我哦，白白',
    tablewareTaskTrick: '您缺少的餐具來啦，在第%d層\n請自己拿取呀',
    tablewareTaskTrickTts: '您缺少的餐具來啦，在第%d層，請自己拿取呀',
    okGetTaskHandle: '好的，收到任務啦，我這就去處理',
    netError: '網絡异常',
    taskHandleComplete: '任務已經處理完啦',
    taskTakeTTS: '任務領取成功，請選擇要用什麼方式處理哦',
    humanReplyTTS: '%s桌%s任務已經處理完成啦，請儘快回復顧客呀',
    humanDeliveryTTS: '%s桌缺少餐具的任務已經處理完成啦，請儘快拿給顧客哦',
    tablewareEnterTTS: '點擊荧幕選擇您需要的餐具，用加號按鈕選擇數量，選好後，記得選擇下方的完成按鈕哦',
    hurryTaskCompleteTTS: '您剛才讓我幫您催菜，我已經幫您催過啦，服務人員說馬上就好哦，請再等一小會兒吧',
    waiterTaskCompleteTTS: '您剛才讓我幫您找服務人員，我已經幫您通知到啦，他們馬上就來，請稍等一小會兒哦',
    clearTableTaskCompleteTTS: '您的收拾桌子任務，已經幫您通知服務人員啦，他們馬上就來，請稍等哦',
    tierPickTitle: '層數選擇',
    tierPickSubTitle: '請選擇放置餐具的層數',
    robotReplayTTS: '點擊下方開始執行按鈕，我就幫你去回復顧客啦',
    robotDeliveryTTS: '點擊下方開始執行按鈕，我就幫你送餐具給顧客啦',
    errorToast: '由於網絡同步問題，該任務已被其他人搶先處理，您無需理會（%s）',
    taskDialogTTS: '請確認您的桌號和任務是否正確',
    callPositionTTS: '點擊或語音選擇您需要的服務，小豹都可以完成哦',
    yes: '是',
    no: '否',
    birthday1TTS: '%s，你好呀，祝你生日快樂，您的%s，%s，想對你說：%s',
    thanksYouCanGo: '謝謝，你可以走了',
    convertHurryTaskTTS: '好嘞，我這就幫您催菜去',
    convertTablewareTaskTTS: '好噠，我這就去找服務人員，幫您準備餐具啦',
    convertWaiterTaskTTS: '收到，我去幫你找服務人員去啦',
    convertClearTaskTTS: '好嘞，我這就去幫您通知服務人員來收拾桌子',
    goWayCallMe: '我走啦，有需要可以隨時再叫我哦',
    birthdayLocalAsrArray: [
        '謝謝你可以走了',
        '你可以走了',
        '再見',
        '謝謝',
        '不用了',
        '走吧'
    ],
    cannotArriveTip: '*當前餐桌，機器人無法到達',
    deskSettings: '跑堂設定',
    nav_multiRobotError_tts: '多機調度出現異常，請嘗試重啓或聯系售後人員',
    // eslint-disable-next-line @typescript-eslint/camelcase
    warningHint_multiRobotError: '請對此畫面拍照並聯系售後人員',
    // eslint-disable-next-line @typescript-eslint/camelcase
    warningTitle_multiRobotError: '多機調度出現異常',
    deskService: '跑堂',
    warningTitlePathInvalid: '我沒有找到巡線',
    warningSubTitlePathInvalid: '請繪制巡線並發布',
    warningTitleRobotOutOfPath: '我脫離巡線了',
    warningSubTitleRobotOutOfPath: '請把我推到巡線范圍內',
    waringTitleTargetOutOfPath: '目的地不在巡線范圍內',
    warningSubTitleTargetOutOfPath: '請檢查巡線並重新發布'
};